FastFoot.Web.UI/Controllers/FaqController.cs
using Microsoft.AspNetCore.Mvc;

namespace FastFoot.Web.UI.Controllers
{
    public class FaqController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FastFoot.Web.UI/ViewComponents/SendMessageViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace FastFoot.Web.UI.ViewComponents
{
    public class SendMessageViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

FastFoot.Web.UI/Views/Faq/Index.cshtml
<div class="breadcumb-wrapper"
     data-bg-src="asset/img/breadcumb/breadcumb-bg.jpg">
    <div class="container z-index-common">
        <div class="breadcumb-content">
            <h1 class="breadcumb-title">Asked Questions</h1>
            <ul class="breadcumb-menu">
                <li><a href="index.html">Home</a></li>
                <li>FAQ</li>
            </ul>
        </div>
    </div>
</div>
<div class="overflow-hidden space" style="margin-bottom:120px;">
    <div class="container">
        <div class="title-area text-center">
            <span class="sub-title">Customer Questions</span>
            <h2 class="sec-title">Frequently asked questions</h2>
        </div>
        <div class="row gy-4 align-items-center">
            <div class="col-lg-6">
                <div class="accordion" id="faqAccordion">
                    <div class="accordion-card style2">
                        <div class="accordion-header" id="collapse-item-1">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse-1"
                                    aria-expanded="false"
                                    aria-controls="collapse-1">
                                How Does This Work?
                            </button>
                        </div>
                        <div id="collapse-1"
                             class="accordion-collapse collapse"
                             aria-labelledby="collapse-item-1"
                             data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-card style2 active">
                        <div class="accordion-header" id="collapse-item-2">
                            <button class="accordion-button"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse-2"
                                    aria-expanded="true"
                                    aria-controls="collapse-2">
                                Does your pizza contain peanuts or peanut oil?
                            </button>
                        </div>
                        <div id="collapse-2"
                             class="accordion-collapse collapse show"
                             aria-labelledby="collapse-item-2"
                             data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-card style2">
                        <div class="accordion-header" id="collapse-item-3">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse-3"
                                    aria-expanded="false"
                                    aria-controls="collapse-3">
                                Are your doughs vegan or vegetarian friendly?
                            </button>
                        </div>
                        <div id="collapse-3"
                             class="accordion-collapse collapse"
                             aria-labelledby="collapse-item-3"
                             data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-card style2">
                        <div class="accordion-header" id="collapse-item-4">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse-4"
                                    aria-expanded="false"
                                    aria-controls="collapse-4">
                                Does your pepperoni contain gluten?
                            </button>
                        </div>
                        <div id="collapse-4"
                             class="accordion-collapse collapse"
                             aria-labelledby="collapse-item-4"
                             data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="accordion" id="faqAccordion2">
                    <div class="accordion-card style2 active">
                        <div class="accordion-header" id="collapse-item2-1">
                            <button class="accordion-button"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse2-1"
                                    aria-expanded="true"
                                    aria-controls="collapse2-1">
                                Where I Can Find The Menu?
                            </button>
                        </div>
                        <div id="collapse2-1"
                             class="accordion-collapse collapse show"
                             aria-labelledby="collapse-item2-1"
                             data-bs-parent="#faqAccordion2">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-card style2">
                        <div class="accordion-header" id="collapse-item2-2">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse2-2"
                                    aria-expanded="false"
                                    aria-controls="collapse2-2">
                                Some menus are missing on a restaurant page?
                            </button>
                        </div>
                        <div id="collapse2-2"
                             class="accordion-collapse collapse"
                             aria-labelledby="collapse-item2-2"
                             data-bs-parent="#faqAccordion2">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-card style2">
                        <div class="accordion-header" id="collapse-item2-3">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse2-3"
                                    aria-expanded="false"
                                    aria-controls="collapse2-3">
                                Can I order from different restaurant?
                            </button>
                        </div>
                        <div id="collapse2-3"
                             class="accordion-collapse collapse"
                             aria-labelledby="collapse-item2-3"
                             data-bs-parent="#faqAccordion2">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-card style2">
                        <div class="accordion-header" id="collapse-item2-4">
                            <button class="accordion-button collapsed"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse2-4"
                                    aria-expanded="false"
                                    aria-controls="collapse2-4">
                                How to Go Caferio Restaurnt by Road?
                            </button>
                        </div>
                        <div id="collapse2-4"
                             class="accordion-collapse collapse"
                             aria-labelledby="collapse-item2-4"
                             data-bs-parent="#faqAccordion2">
                            <div class="accordion-body">
                                <p class="faq-text">
                                    In general, the painting process involves several steps
                                    that need to be done carefully and precisely to ensure a
                                    high-quality, long-lasting finish. These steps may include
                                    preparing the surface by sanding and cleaning it
                                    thoroughly, Applying a primer coat to help the paint
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@await Component.InvokeAsync("SendMessage")
@await Component.InvokeAsync("FoodsCarusel")